- name: Ensure dependencies for the XHProf UI are present.
  package: "name={{ item }} state=installed"
  with_items:
    - graphviz

- name: Download and untar XHProf.
  unarchive:
    src: "{{ xhprof_download_url }}"
    dest: "{{ workspace }}"
    copy: no
    creates: "{{ workspace }}/{{ xhprof_download_folder_name }}"

- name: Move XHProf PHP library into place.
  shell: >
    cp -r {{ workspace }}/{{ xhprof_download_folder_name }}/xhprof_lib {{ php_xhprof_lib_dir }}
    creates={{ php_xhprof_lib_dir }}/utils/xhprof_lib.php

- name: Move XHProf UI into place.
  shell: >
    cp -r {{ workspace }}/{{ xhprof_download_folder_name }}/xhprof_html {{ php_xhprof_html_dir }}
    creates={{ php_xhprof_html_dir }}/index.php
- include: configure.yml
